nginx:
    image: nginx
    links:
     - dotclear:fpm
    volumes:
     - ./fpm/fpm.conf:/etc/nginx/conf.d/default.conf:Z
    volumes_from:
     - blog_data
    restart: always

mysql:
    image: mysql
    volumes_from:
     - mysql_data
    restart: always

dotclear:
    image: darknao/dotclear:fpm
    links:
     - mysql:mysqldb
    volumes_from:
     - blog_data
    restart: always

varnish:
    image: eeacms/varnish
    links:
     - nginx
    volumes:
     - ./varnish:/etc/varnish/conf.d:Z
    ports:
     - "8106:80"
    restart: always
